; tpost1.g
; called after tool 1 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.16 on Thu Aug 24 2023 22:40:38 GMT+0200 (Central European Summer Time)

M98 P"atcPickup.g" S1
M98 P"atcProbeZ.g" S1