; tfree0.g
; called when tool 0 is freed
;
; generated by RepRapFirmware Configuration Tool v3.3.16 on Thu Aug 24 2023 22:40:38 GMT+0200 (Central European Summer Time)

; Nothing to do as tool 0 = no tool
;M98 P"atcDrop.g" S0