; tfree4.g
; called when tool 4 is freed
;
; generated by RepRapFirmware Configuration Tool v3.3.16 on Thu Aug 24 2023 22:40:38 GMT+0200 (Central European Summer Time)

if {exists(global.dustShoeEngaged)}
	M98 P"dustShoeRetract.g"
M98 P"atcDrop.g" S4