; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.16 on Thu Aug 24 2023 22:40:38 GMT+0200 (Central European Summer Time)

; Nothing to do as tool 0 = no tool
;M98 P"atcPickup.g" S0
;M98 P"atcProbeZ.g" S0