; tpre7.g
; called before tool 7 is selected
;
; generated by RepRapFirmware Configuration Tool v3.3.16 on Thu Aug 24 2023 22:40:38 GMT+0200 (Central European Summer Time)

;M98 P"atcPickup.g" S7